### ISSUE TITLE
Latest release fails to build Java project

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1323] opened 2017-05-04 18:41 UTC
I recently upgraded to the latest version (`buck-2017.05.04.01`) on macOS. 

I get the following error on a project that previously built: 

> Warning raised by BUCK file parser: ImportError: No module named buck_parser
> No content to map due to end-of-input
>  at [Source: com.google.common.io.CountingInputStream@36def8d4; line: 1, column: 0]

Any ideas?

**Comment by aiked** [comment] 2017-05-05 09:09
Looking into this.

**Comment by njlr** [comment] 2017-05-05 10:58
As a work-around you can install an old version. For example: 

```
brew unlink buck
brew install https://raw.githubusercontent.com/facebook/homebrew-fb/7511722fd58e999e5d8c3a415d4e8cd1deee8f21/buck.rb 
```

**Comment by kageiit** [comment] 2017-05-05 13:50
This usually happens when you have an old daemon hanging around from the previous version. We found that `buck kill` or `killall java` (more extreme) to get rid of any old buck daemon processes usually resolves this

**Comment by kageiit** [comment] 2017-05-05 13:52
@aiked it might be wise to invest time into killing old buck daemons after a buck update from brew or `.buckversion`. Currently we do this in our `buckw` for okbuck, and have not seen this issue ever since we started doing that

**Comment by njlr** [comment] 2017-05-05 14:07
I ran the following to get the latest version working: 

```
# Installed an old version
brew unlink buck
brew install https://raw.githubusercontent.com/facebook/homebrew-fb/7511722fd58e999e5d8c3a415d4e8cd1deee8f21/buck.rb

# Your suggestion
buck kill

# Install latest
brew unlink buck
brew install --HEAD facebook/fb/buck 
```

So it may have been the reinstall or `buck kill` (or both!) that did the trick.

**Comment by aiked** [comment] 2017-05-05 14:20
@njlr You installed v2017.03.29.01, which is the last working one. I can reproduce the issue in this case, it looks like there is an issue during the bottling of the binary.

@kageiit Makes sense, we should do that. For this specific case, I don't think that the problem is the old buck running.

**Comment by aiked** [comment] 2017-05-08 17:02
Update: the issue has been resolved internally but for unrelated reasons open-source buck is a bit behind, I expect this to be resolved tomorrow and a new working version to be out soon.

**Comment by aiked** [comment] 2017-05-09 12:10
New release: https://github.com/facebook/buck/releases/tag/v2017.05.09.01
I checked that is working but tell me if something is weird.

**Closed by aiked** 2017-05-09 12:10 UTC

**Comment by CzokNorris** [comment] 2017-09-13 11:41
I am still seeing this issue when building https://github.com/deezer/weslang

**Comment by ttsugriy** [comment] 2017-09-13 22:46
@CzokNorris, which target are you trying to build? Can you please provide repro steps?

**Comment by ttsugriy** [comment] 2017-09-13 22:48
```
/usr/local/Cellar/buck/2017.09.04.02/bin/buck build java/com/deezer/research/language:detection_service_interface
```
works for me, so I don't think there are any issues with latest release.
