### ISSUE TITLE
Is someone finished buck build on windows_X64 OS

### ISSUE THREAD

**Issue by aqiang11** [facebook/buck#2489] opened 2020-07-01 02:24 UTC
I got a problem when build buck on windows
Command failed with exit code 1.

stderr:
    When running <javac>.
    When building rule //src/com/facebook/buck/jvm/java/abi/kotlin:kotlin.

**Comment by v-jizhang** [comment] 2020-07-01 18:55
This is a duplicate of #2466.

**Closed by v-jizhang** 2020-07-01 18:55 UTC
