### ISSUE TITLE
invalidate cache when a dependency is removed

### ISSUE THREAD

**Issue by jauco** [facebook/buck#1015] opened 2016-11-14 13:22 UTC
Steps to reproduce

1. Make some valid buck rule with a required dependency
2. run `buck build //therule`
3. remove the dependency
4. run `buck build //therule`. The build succeeds!? (cached result)
5. run `rm -rf buck-out && buck build //therule` the build fails!

So I'm able to bring buck in a state where a clean build would have a different result from a non-clean build. Is this also how it works for you or did I do something wrong? (I was experimenting with buck at the time so I might have done something weird)

Is this by design? it did surprise me.

**Comment by sdwilsh** [comment] 2016-11-14 17:30
Could you provide an example?  I would expect that to invalidate things, 
so having a reproducible example would help figure out if there's a bug 
in a specific rule or possibly something else.

**Comment by jauco** [comment] 2016-11-14 20:39
I'll get to it tomorrow morning.

-- 
Jauco
Op ma 14 nov. 2016 om 18:30 schreef Shawn Wilsher <notifications@github.com>

**Comment by jauco** [comment] 2016-11-16 09:02
I've pushed to the branch BUCK of https://github.com/huygensING/timbuctoo with a repo that you should be able to use to reproduce the problem.

A transcript of how I triggered it is below:

```
┌─[±][BUCK ✓][timbuctoo-buck-issue][]
└─▪ buck fetch timbuctoo-instancev4 && buck build timbuctoo-instancev4
[-] PROCESSING BUCK FILES...FINISHED 0.6s [100%]
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 44.3s [100%] (1/1 JOBS, 1 UPDATED, 1 [100.0%] CACHE MISS)
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 46.9s [100%] (451/451 JOBS, 450 UPDATED, 450 [99.8%] CACHE MISS)
┌─[±][BUCK ✓][timbuctoo-buck-issue][]
└─▪ vim timbuctoo-instancev4/BUCK
┌─[±][BUCK U:1 ✗][timbuctoo-buck-issue][]
└─▪ git diff
diff --git a/timbuctoo-instancev4/BUCK b/timbuctoo-instancev4/BUCK
index 69cd8ff..7709aaa 100644
--- a/timbuctoo-instancev4/BUCK
+++ b/timbuctoo-instancev4/BUCK
@@ -18,7 +18,6 @@ java_library(
     "//third-party/neo4j:neo4j-tinkerpop-api",
     "//third-party/poi:poi-ooxml-schemas",
     "//third-party/commons-configuration:commons-configuration",
-    "//third-party/xmlbeans:xmlbeans",
     "//third-party/commons:commons-lang3",
     "//third-party/commons-lang:commons-lang",
     "//third-party/core:jersey-server",
@@ -65,4 +64,4 @@ java_library(
     "//third-party/tinkerpop:neo4j-gremlin",
     "//third-party/xml-apis:xml-apis"
   ]
-)
\ No newline at end of file
+)
┌─[±][BUCK U:1 ✗][timbuctoo-buck-issue][]
└─▪ buck build timbuctoo-instancev4
[-] PROCESSING BUCK FILES...FINISHED 0.1s [100%] 🐌  File removed
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.7s [100%] (397/397 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
```

So that's what was unexpected. To show that the build ought to fail I'll remove the buck-out and do a rebuild

```
┌─[±][BUCK U:1 ✗][timbuctoo-buck-issue][]
└─▪ rm -r buck-out/
┌─[±][BUCK U:1 ✗][timbuctoo-buck-issue][]
└─▪ buck fetch timbuctoo-instancev4 && buck build timbuctoo-instancev4
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 39.2s [100%] (1/1 JOBS, 1 UPDATED, 1 [100.0%] CACHE MISS)
[-] PROCESSING BUCK FILES...FINISHED 0.1s 🐇
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...24.6s [99%] (450/451 JOBS, 168 UPDATED, 168 [37.3%] CACHE MISS)
 |=> //timbuctoo-instancev4:timbuctoo-instancev4...  8.9s (running javac[8.8s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/dto/dataset/VresDto.java:14: mandatory_warning: Avoid introduction of fields (except constants) in abstract value types
  private Map<String, Collection> collectionsByName;
                                  ^
/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/dto/dataset/VresDto.java:15: mandatory_warning: Avoid introduction of fields (except constants) in abstract value types
  private Map<String, Collection> collectionsByType;
                                  ^
/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/bulkupload/loaders/excel/styleawarexlsxloader/StylesMapper.java:28: error: cannot access org.apache.xmlbeans.XmlObject
    final NodeList styleNodes = styles.getCTStylesheet().getDomNode().getChildNodes();
                                                        ^
  class file for org.apache.xmlbeans.XmlObject not found
/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TinkerpopGraphManager.java:-1: note: Some input files use or override a deprecated API.

/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TinkerpopGraphManager.java:-1: note: Recompile with -Xlint:deprecation for details.

/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/bulkupload/savers/TinkerpopSaver.java:-1: note: Some input files use unchecked or unsafe operations.

/Users/jauco/Documents/timbuctoo-buck-issue/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/bulkupload/savers/TinkerpopSaver.java:-1: note: Recompile with -Xlint:unchecked for details.

Errors: 1. Warnings: 2.

Rule //timbuctoo-instancev4:timbuctoo-instancev4 has failed to build.
org.apache.xmlbeans.XmlObject
Try adding the following deps:
//third-party/xmlbeans:xmlbeans

```

**Comment by jauco** [comment] 2017-08-23 08:28
I'd like to remove this branch from my repository. I ended up not using buck. Do you want me to keep it around?

**Comment by v-jizhang** [comment] 2020-03-03 23:27
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.

**Closed by v-jizhang** 2020-03-03 23:27 UTC
