### ISSUE TITLE
glob() seems to low case file names in some cases

### ISSUE THREAD

**Issue by davido** [facebook/buck#248] opened 2015-02-08 19:04 UTC
Problem with `glob` results in failing `gwt_binary()` rule on other platform. Consider the following rule:

```
java_library(
  name = 'plugin-lib42',
  srcs = glob(['java/' + 'org/ostrovsky/buck/Main.java']),
  resources = glob(['java/**/*.java']),
  deps = [':commons-io'],
)
```

Files that were explicitly listed in the `glob()` included set are low cased:

```
buck.cmd targets --json :plugin-lib42
[-] PARSING BUCK FILES...FINISHED 0,0s
[
{
  "annotationProcessorDeps" : [ ],
  "annotationProcessorOnly" : null,
  "annotationProcessorParams" : [ ],
  "annotationProcessors" : [ ],
  "buck.base_path" : "",
  "deps" : [ ":commons-io" ],
  "exportedDeps" : [ ],
  "extraArguments" : [ ],
  "javac" : null,
  "javacJar" : null,
  "name" : "plugin-lib42",
  "postprocessClassesCommands" : [ ],
  "proguardConfig" : null,
  "providedDeps" : [ ],
  "resources" : [ "java\\org\\ostrovsky\\buck\\Main.java" ],
  "resourcesRoot" : null,
  "source" : null,
  "srcs" : [ "java\\org\\ostrovsky\\buck\\main.java" ],
  "target" : null,
  "type" : "java_library",
  "visibility" : [ ]
}
]
```

When wildcard pattern is used, then the case of files is preserved:

```
java_library(
  name = 'plugin-lib',
  srcs = glob(['java/**/*.java']),
  resources = glob(['java/**/*.java']),
  deps = [':commons-io'],
)
```

```
buck.cmd targets --json :plugin-lib
[-] PARSING BUCK FILES...FINISHED 0,0s
[
{
  "annotationProcessorDeps" : [ ],
  "annotationProcessorOnly" : null,
  "annotationProcessorParams" : [ ],
  "annotationProcessors" : [ ],
  "buck.base_path" : "",
  "deps" : [ ":commons-io" ],
  "exportedDeps" : [ ],
  "extraArguments" : [ ],
  "javac" : null,
  "javacJar" : null,
  "name" : "plugin-lib",
  "postprocessClassesCommands" : [ ],
  "proguardConfig" : null,
  "providedDeps" : [ ],
  "resources" : [ "java\\org\\ostrovsky\\buck\\Main.java" ],
  "resourcesRoot" : null,
  "source" : null,
  "srcs" : [ "java\\org\\ostrovsky\\buck\\Main.java" ],
  "target" : null,
  "type" : "java_library",
  "visibility" : [ ]
}
]
```

**Comment by davido** [comment] 2015-02-08 21:32
This diff fixed this:

```
diff --git a/third-party/py/pathlib/pathlib.py b/third-party/py/pathlib/pathlib.py
index 02448b3..3f43ea1
--- a/third-party/py/pathlib/pathlib.py
+++ b/third-party/py/pathlib/pathlib.py
@@ -1034,7 +1034,7 @@ class Path(PurePath):
         """Iterate over this subtree and yield all existing files (of any
         kind, including directories) matching the given pattern.
         """
-        pattern = self._flavour.casefold(pattern)
+        #pattern = self._flavour.casefold(pattern)
         drv, root, pattern_parts = self._flavour.parse_parts((pattern,))
         if drv or root:
             raise NotImplementedError("Non-relative patterns are unsupported")
```

**Comment by davido** [comment] 2015-02-08 22:16
Another problem is to be able to specify exclusion set in platform independent way. Currently this doesn't seem to work:

```
SRC = 'java/'
EXCLUDES = [SRC + 'org/ostrovsky/buck/Util.java']

java_library(
  name = 'plugin-lib',
  srcs = glob([SRC + '**/*.java'], excludes = EXCLUDES),
  resources = glob(['java/**/*.java']),
  deps = [':commons-io'],
)
```
Doesn't have any effect, `Util.java` wasn't excluded from the sources set:
```
[...]
"srcs" : [ "java\\org\\ostrovsky\\buck\\Main.java", "java\\org\\ostrovsky\\buck\\Util.java" ],
[...]
```
Changing the path delimiter in exclusion set to :
```
SRC = 'java\\'
EXCLUDES = [SRC + 'org\\ostrovsky\\buck\\Util.java']
```
fixed this. Now exclusion set does have effect:
```
"srcs" : [ "java\\org\\ostrovsky\\buck\\Main.java" ],
```

I think that `glob()` should accept exclusion set with posix like paths and it should work on all supported platforms.

**Comment by sdwilsh** [comment] 2015-03-02 14:56
Regarding the casefolding part: https://msdn.microsoft.com/en-us/library/aa365247%28v=vs.85%29.aspx is the spec, and it says:

> Do not assume case sensitivity. For example, consider the names OSCAR, Oscar, and oscar to be the same, even though some file systems (such as a POSIX-compliant file system) may consider them as different. Note that NTFS supports POSIX semantics for case sensitivity but this is not the default behavior.

Are you, by chance, on a case-sensitive file system on Windows?  We might have to add some config check or something to support that non-default state.

As for the path separator, I agree that we should just use unix-style in BUCK files.  It looks like it should work, so I'm wondering if you are failing this check: https://github.com/facebook/buck/blob/master/third-party/py/pathlib/pathlib.py#L595

**Comment by davido** [comment] 2015-03-02 19:18
So i was able to track down the problem and fix it. There was separator char mismatch between exlusion pattern supplied to the `glob()` (always posix) and the path that was returned from twitter's `pythonlib` library (oathe platform flavour). So the solution is one liner:

```
diff --git a/src/com/facebook/buck/parser/buck.py b/src/com/facebook/buck/parser/buck.py
index 0a7f7e6..9859b6d
--- a/src/com/facebook/buck/parser/buck.py
+++ b/src/com/facebook/buck/parser/buck.py
@@ -150,7 +150,7 @@ def glob_internal(includes, excludes, include_dotfiles, allow_empty, search_base
             non_special_excludes.add(pattern)

     def exclusion(path):
-        if str(path) in non_special_excludes:
+        if path.as_posix() in non_special_excludes:
             return True
         for pattern in match_excludes:
             result = path.match(pattern, match_entire=True)
```

**Comment by sdwilsh** [comment] 2015-03-03 11:09
That only addresses the exclude issue, and not the case issue, right?

**Comment by davido** [comment] 2015-03-03 12:04
Yes. That's because the case issue was solved in this patch: [1].

[1] https://github.com/davido/gerrit-buck-patch/blob/master/buck_gerrit.patch#L113,L134

**Comment by sdwilsh** [comment] 2015-03-03 12:25
So it's not blocking you, but we don't have a fix here yet ;)

**Comment by davido** [comment] 2015-03-03 12:35
Actually it's blocking me. The plan is to upstream this patch: [1] to support Gerrit build on other platform out of the box [2]. And not to require folks to patch Buck. With the provided reproducer, are you able to reproduce the problem?

[1] https://github.com/davido/gerrit-buck-patch/blob/master/buck_gerrit.patch
[2] https://gerrit-review.googlesource.com/65600

**Comment by sdwilsh** [comment] 2015-03-04 17:18
I'm trying to understand why the case difference matters.  Simply not casefolding, as your suggested patch does, isn't okay because `pathlib` may need to compare paths, and that's how it does so on Windows because the file system isn't case sensitive.  `java/org/ostrovsky/buck/Main.java` and `java/org/ostrovsky/buck/main.java` should be equivalent on Windows.

What bug are you actually seeing?

**Comment by sdwilsh** [comment] 2015-03-04 19:33
This is a test case that reproduces your bug, however:

```diff
diff --git a/src/com/facebook/buck/parser/buck_test.py b/src/com/facebook/buck/parser/buck_test.py
index 13e47c6..215d109 100644
--- a/src/com/facebook/buck/parser/buck_test.py
+++ b/src/com/facebook/buck/parser/buck_test.py
@@ -258,6 +258,25 @@ class TestBuck(unittest.TestCase):
         finally:
             shutil.rmtree(d)

+    def test_case_preserved(self):
+        d = tempfile.mkdtemp()
+        try:
+            subdir = os.path.join(d, 'java')
+            os.makedirs(subdir)
+            open(os.path.join(subdir, 'Main.java'), 'w').close()
+            self.assertEquals(
+                [
+                    os.path.join('java', 'Main.java'),
+                ],
+                glob_internal(
+                    includes=['java/Main.java'],
+                    excludes=[],
+                    include_dotfiles=False,
+                    allow_empty=False,
+                    search_base=Path(d)))
+        finally:
+            shutil.rmtree(d)
+
```

**Comment by davido** [comment] 2015-03-05 07:35
It doesn't really matter that other platform is not case sensitive, Java compiler is case sensitive, though. `gwt_binary()` is failing because of case mismatch between file and the class name defined in this file: `foo.java` defines class `Foo`. What happens, is:

* `Foo.java` is put in resource set with full path
* Because of `pathlib.py` bug, the case of the file is changed to `foo.java`
* wrong case is stored in output artifact `foo_module.jar`, that is input to `gwt_binary()`
* `gwt_binary()` uses the files from the GWT module created in previous step and pass them to the GWT compiler
* GWT compiler is failing with: `The public type Foo must be defined in its own file`

To see the failure, source files must be added without wildcard pattern:

```
SRC = 'src/main/java/com/google/gerrit/extensions/client/'
EXT_API_SRCS = glob([
  SRC + 'ChangeStatus.java',
  SRC + 'Comment.java',
  SRC + 'GerritTopMenu.java',
  SRC + 'InheritableBoolean.java',
  SRC + 'ListChangesOption.java',
  SRC + 'ProjectState.java',
  SRC + 'Side.java',
  SRC + 'SubmitType.java',
  SRC + 'Theme.java']
)
```

Now `gwt_module()` is created and is broken:

```
gwt_module(
  name = 'client',
  srcs = EXT_API_SRCS,
  gwt_xml = SRC + 'Extensions.gwt.xml',
  visibility = ['PUBLIC'],
)
```

It can be observed, that resource set entries are low cased: http://paste.openstack.org/show/188694.
And as the consequence the files are put with wrong case in the resulting output artifact, that is input for `gwt_binary()`: http://paste.openstack.org/show/188728.  But this causes `gwt_binary()` invocation (GWT compiler call) to fail with case mismatch error: http://paste.openstack.org/show/188710.

Ironically the work around is to replace the full paths with wildcard pattern:

```
EXT_API_SRCS = glob([SRC + 'client/*.java'])
```

With wildcard pattern the case of files is preserved. But i think this should just work in both cases, and the way the resource set was created, shouldn't make any difference.

**Comment by sdwilsh** [comment] 2015-03-05 11:27
In your case, you can just stop using `glob` since you are specifying files anyway.  I'm looking at fixing pathlib here, but if you don't need `glob`, you shouldn't use it to list your `srcs` anyway.

**Comment by sdwilsh** [comment] 2015-03-05 17:52
The proper fix for this actually does involve removing those lines you commented out, but other changes are needed for it to be the right fix still.  I just landed this internally; should go out tomorrow at some point.

**Comment by davido** [comment] 2015-03-05 17:58
I wonder if this fix should be done upstream?

**Comment by sdwilsh** [comment] 2015-03-05 18:03
Yes, and at some point we'll get our set of fixes we've done to the library there, but for now, getting it in here is good enough.  If you want to help get it upstream, that'd be really nice, but not expected.

**Closed** 2015-03-06 15:03 UTC
