### ISSUE TITLE
Performance issues with buck apk

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#826] opened 2016-07-31 01:50 UTC
We are noticing an issue with buck where the apk it creates does not run smoothly compared to the grade one. This is especially noticeable with animations. we verified that the mindSdk and targetSdk versions were set correctly (ref #392) and that we have opengl version 2 required in the manifest.

Here is the `aapt dump xmltree` for the buck apk

```
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=1)
    A: android:versionCode(0x0101021b)=(type 0x10)0x0
    A: android:versionName(0x0101021c)="example" (Raw: "example")
    A: package="com.example" (Raw: "com.example")
    A: platformBuildVersionCode=(type 0x10)0x18 (Raw: "24")
    A: platformBuildVersionName=(type 0x4)0x40e00000 (Raw: "7.0")
    E: uses-feature (line=2)
      A: android:glEsVersion(0x01010281)=(type 0x11)0x20000
      A: android:required(0x0101028e)=(type 0x12)0xffffffff
    E: uses-sdk (line=17)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0xf
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x18
```

and here it is for the gradle apk

```
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionName(0x0101021c)="example" (Raw: "example")
    A: package="com.example" (Raw: "com.example")
    A: platformBuildVersionCode=(type 0x10)0x18 (Raw: "24")
    A: platformBuildVersionName=(type 0x4)0x40e00000 (Raw: "7.0")
    E: uses-sdk (line=6)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0xf
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x18
    E: uses-feature (line=10)
      A: android:glEsVersion(0x01010281)=(type 0x11)0x20000
      A: android:required(0x0101028e)=(type 0x12)0xffffffff
```

**Comment by marcinkosiba** [comment] 2016-08-01 11:31
Sorry, this isn't very actionable. I don't think remote-debugging a perf issue in a codebase I don't have access to is a good use of our time. Please re-open this once you've narrowed down the root cause.

Here are some questions to get you started: have you confirmed your app is running hw-accelerated? Maybe the resources for the needed dpi are not included?

**Comment by hzsweers** [comment] 2016-08-01 11:53
Would it be a good use of your time if we provided a sample? We've determined about as much as we can on our end. Hardware acceleration is enabled, this animation has no image assets being used that would be DPI dependent. It's just a simple view with a color background having its width and x location animated with a value animator. 

It'd be great if you left the issue open as well, as it's not actually resolved and closing it hides it from others that might see it and have relevant input.

**Comment by marcinkosiba** [comment] 2016-08-01 15:00
> Would it be a good use of your time if we provided a sample?

My comment was just about your time (well, @kageiit's) as it was mine. A sample would be helpful, especially that it seems like you already have this isolated to a simple scenario.

**Closed** 2020-03-04 00:04 UTC
