### ISSUE TITLE
header_path_prefix can't be set "

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1199] opened 2017-02-22 12:29 UTC
When I set `header_path_prefix = ''` for `apple_library`, it build error. If `header_path_prefix` don't set as` ''`, the code can be built correctly.
Build rule likes this:
```
apple_library(
  name = 'demo',
  header_path_prefix = '',
  preprocessor_flags = ['-fobjc-arc'],
  headers = glob(['Class/*.h']),
  srcs = glob(['Class/*.m']),
)
```

The error messages likes this:
Multiple entries with same key: HotWordsViewController.h=/Users/baidu/Desktop/code/Widgets/HotWords/Class/HotWordsViewController.h and HotWordsViewController.h=/Users/baidu/Desktop/code/Widgets/HotWords/Class/HotWordsViewController.h

**Comment by Coneko** [comment] 2017-02-22 16:32
Are you sure that's all you have in your target? That error happens when you specify the same header in `headers` and `exported_headers` too I think.

**Comment by SwiftlyFly** [comment] 2017-02-23 03:05
I just configured headers in my target, [Here](https://github.com/SwiftlyFly/header_path_prefix_demo) is a demo that the error will happen. You can build target `//ViewController:ViewController`.

**Comment by wdsunny** [comment] 2017-08-23 11:24
I have same issue, anyone find solution?

**Comment by ttsugriy** [comment] 2017-08-23 17:04
Apologies for the delay. I'm going to take a look today.

**Comment by ttsugriy** [comment] 2017-08-23 17:05
Also, I appreciate the repro @SwiftlyFly!

**Comment by ttsugriy** [comment] 2017-08-23 21:05
So the problem is that header file map already includes files without header_path_prefix for usage within the same target, so trying to add an explicit `header_path_prefix` leads to a duplicate. I have a fix for this internally, but technically simply removing the `header_path_prefix` should also work.

**Comment by ttsugriy** [comment] 2017-08-24 06:00
[https://github.com/facebook/buck/commit/9fb6b338bbbdb6a513647c27c4ecdbc712038f09](My changes) should have fixed this problem. I'm closing the task, but if you still experience any issues, please feel free to reopen this task.

**Comment by ttsugriy** [comment] 2017-08-25 20:17
I had to temporarily revert my changes, but I have a new changeset which I hope to commit today.

**Comment by ttsugriy** [comment] 2017-08-26 20:19
[new fix](https://github.com/facebook/buck/commit/4a4bf25802ccad0b71f4f9bfde1aeb00a57a3277) has landed. Closing the issue.

**Closed by ttsugriy** 2017-08-26 20:19 UTC
