### ISSUE TITLE
Looking for Android build tools when building non-android project

### ISSUE THREAD

**Issue by finik** [facebook/buck#905] opened 2016-09-28 06:54 UTC
While following instructions to build gerrit-oauth-provider
https://github.com/davido/gerrit-oauth-provider.git (which is not related to android in any way)

Got this:
buck build plugin
No Android platform target specified. Using default: Google Inc.:Google APIs:23
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.3s [13%](3/16 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
BUILD FAILED: android-4.4W in null is not a valid build tools directory.
Build tools directories should be follow the naming scheme: android-<VERSION>, build-tools-<VERSION>, or <VERSION>. Please remove directory android-4.4W.

@davido (the author of gerrit-oauth-provider) suggested I open an issue for buck.

**Comment by davido** [comment] 2016-09-28 06:56
CC @Coneko. Can you have a look? Thanks!

**Comment by davido** [comment] 2016-09-28 06:57
@finik Can you add Buck version you are using?

**Comment by finik** [comment] 2016-09-28 06:59
buck --version
buck version v2016.09.26.01

env | grep -i android
ANDROID_HOME=/Users/finik/work/android-sdk
ANDROID_SDK_ROOT=/Users/finik/work/android-sdk
PATH=/Users/finik/perl5/bin:/usr/local/Cellar/ruby/1.9.3-p327/bin/:/usr/local/share/npm/bin/:/Users/finik/bin:/usr/local/bin:/usr/local/sbin:/Users/finik/work/android-sdk/tools:/Users/finik/work/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

env | grep -i java
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home

**Comment by davido** [comment] 2016-09-28 07:29
I think that Buck is confused with `ANDROID_HOME` and `ANDROID_SDK_ROOT`. When they are set, uck expects specific version of those. Just unsetting these env variables should fix the problem.

**Comment by aiked** [comment] 2016-09-28 12:07
The problem is with https://github.com/facebook/buck/commit/7886e4581651276c255003cce53435fd0c1163b8. I will check it out and see how we can address this.

**Comment by aiked** [comment] 2016-09-28 16:25
@maiergre wrote the diff that changed this logic, maybe he has more knowledge for this one.

**Comment by aiked** [comment] 2017-03-02 14:12
I pushed 2aab2deef16d9151e5a250e8ebdf5eeba5973fc1 that should address a possible issue behind this. Other than that the specific NDK has a weird structure and I think it's causing the issue. I tested with a few different NDKs and I could not reproduce.

I will close this but feel free to re-open if you can provide more info about what is happening.

**Closed by aiked** 2017-03-02 14:12 UTC

**Comment by davido** [comment] 2017-03-02 14:32
Thanks!
