### ISSUE TITLE
does buck support res/values/public.xml?

### ISSUE THREAD

**Issue by coofee** [facebook/buck#864] opened 2016-08-29 07:49 UTC
my application use public.xml and ids.xml to fixed resource id，when i use buck install，it throw error like below，so i want to know whether  buck support public.xml?

> Error parsing resources to generate resource IDs for ~/TestBuck/res.
com.facebook.buck.android.aapt.MiniAapt.ResourceParseException: Invalid resource type '<public>' in 'TestBuck/res/values/public.xml'.
com.facebook.buck.android.aapt.MiniAapt$ResourceParseException: Invalid resource type '<public>' in 'TestBuck/res/values/public.xml'.
       	at com.facebook.buck.android.aapt.MiniAapt.processValuesFile(MiniAapt.java:413)
       	at com.facebook.buck.android.aapt.MiniAapt.processValues(MiniAapt.java:349)
       	at com.facebook.buck.android.aapt.MiniAapt.collectResources(MiniAapt.java:272)
       	at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:166)
       	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
       	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1151)
       	at com.facebook.buck.rules.CachingBuildEngine.access$1000(CachingBuildEngine.java:109)
       	at com.facebook.buck.rules.CachingBuildEngine$5$1.call(CachingBuildEngine.java:523)
       	at com.facebook.buck.rules.CachingBuildEngine$5$1.call(CachingBuildEngine.java:512)
       	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
       	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:61)
       	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
       	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
       	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
       	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)

the file structure like this:

> +res
     + values
           + public.xml
           + ids.xml

and the public.xml content like this 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <public type="anim" name="anim_public_demo" id="0x7f840000" />
    <public type="array" name="array_public_demo" id="0x7f870000" />
</resources>
```

and the ids.xml content like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="anim_public_demo" type="anim" />
    <item name="array_public_demo" type="array" />
</resources>
```

**Comment by aiked** [comment] 2016-08-30 16:50
Hello @coofee,
Probably @marcinkosiba can answer this.

**Comment by marcinkosiba** [comment] 2016-08-30 16:54
Hey! You're correct, buck doesn't support `public.xml`. I think the `public.xml` mechanism was intended for the Android framework in order to keep the resource IDs the same across different SDK versions.
Are you using it because you redistribute an obfuscated .jar file along with some resources?

**Comment by coofee** [comment] 2016-08-31 02:41
Very thanks  @marcinkosiba @aiked

I do not redistribute an obfuscated .jar along with resources, it's because my app has some module, and each module's resources id has different type id.  such as below:

module1: 0x7f070000
module2: 0x7f170000
module3: 0x7f270000

**Comment by aiked** [comment] 2016-09-01 15:42
@coofee I will close this but if it's something you really want we are open to patches :)

**Closed by aiked** 2016-09-01 15:42 UTC

**Comment by coofee** [comment] 2016-09-02 02:07
Thank you very much. @aiked
