### ISSUE TITLE
No library manifests found. Aborting manifest merge step.

### ISSUE THREAD

**Issue by 79144876** [facebook/buck#230] opened 2014-12-31 03:32 UTC
https://github.com/facebook/buck/issues/229
How to fix it ??
Thanks.

**Comment by 79144876** [comment] 2015-01-01 16:40
I have put my project here : https://github.com/79144876/FacebookBuckExample
You can clone it ,and then run buck build.it will error again.
May be you will find some error.
Thanks.

**Comment by sdwilsh** [comment] 2015-01-02 22:53
Is this just a dupe of #229 ?

**Comment by FrancisToth** [comment] 2015-03-24 02:23
Is this still an issue ? I thought this was resolved considering the e-mails we've exchanged. Would it be possible to get the example back ?

**Comment by 79144876** [comment] 2015-03-24 06:51
Sorry.I have fix it.
Thanks.

**Closed** 2015-03-29 23:52 UTC
