### ISSUE TITLE
Added deps on prebuilt_jar rule are not available as expected

### ISSUE THREAD

**Issue by hujin1860** [facebook/buck#457] opened 2015-10-11 11:50 UTC
prebuilt_jar need the exported_deps argument

``` python
prebuilt_jar(
  name = 'retrofit',
  maven_coords = 'com.squareup.retrofit:retrofit:jar:2.0.0-beta2',
  binary_jar = 'retrofit-2.0.0-beta2.jar',
  source_jar = 'retrofit-2.0.0-beta2-sources.jar',
  deps = [
    '//third-party/okhttp:okhttp'
  ],visibility = [
    'PUBLIC'
  ]
)
```

when android_library depend the retrofit jar, can't direct use the okhttp class.

**Comment by sdwilsh** [comment] 2015-10-15 14:22
`deps` on a `prebuilt_jar` are already treated as `exported_deps`.  Can you provide an example that fails?

**Comment by hujin1860** [comment] 2015-10-15 15:20
https://github.com/hujin1860/buck-test
with buck command
``` shell
buck build //app:src
```

**Comment by sdwilsh** [comment] 2015-11-02 22:41
@hujin1860 - that repo is missing files/directories, and I haven't been able to hack it up enough to get it to build.  Can you please try to reproduce it in that repo?

**Comment by hujin1860** [comment] 2015-11-03 03:10
sorry for my mistake, I already fix the problem. Please try it again

**Comment by sdwilsh** [comment] 2015-11-03 18:50
Whoops, I did get to that point yesterday.  I got this issue mixed up with another, so when I hit that build error, I thought it was more broken.

So I can reproduce this.  I'm not sure why it's not working though.

**Comment by sdwilsh** [comment] 2015-11-03 19:02
What version of Buck are you using (the githash or the tag you are using would be sufficient)?

**Comment by hujin1860** [comment] 2015-11-04 06:56
I use homebrew install buck, the version is facebook/fb/buck-2015.10.19.01

**Comment by v-jizhang** [comment] 2020-03-04 01:29
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.

**Closed by v-jizhang** 2020-03-04 01:29 UTC
Labels: bug
