### ISSUE TITLE
about res xml R.java code generation issue

### ISSUE THREAD

**Issue by congling** [facebook/buck#443] opened 2015-10-01 17:07 UTC
Hi,
    I'm trying to migrate my core library projects to BUCK build. However, there're some bugs in the R.java code generation process. 
    
    I've imported jira android client to our project. It includes some keys which contains dot, such like the following file.
    gsp-android-core/res/values/jconnect_droid_strings.xml:    <string name="jconnect.droid.attach">Attach</string>

    However when I use buck to build this project it generates  plenty of such errors.
       android_project/buck-out/bin/gsp-android-core/__gsp-android-core#dummy_r_dot_java_rdotjava_src__/com/happyelements/gsp/android/R.java:48: error: 需要<标识符>
               public static int jconnect.droid.attach=0x07f0101f;

     
    But in the other build system such like gradle in android studio and ant in eclipse, the R.java file would be like the following:
        public static int jconnect_droid_attach=0x7f08003d;

    Is it because of some design purpose to strength the format of the resource files?
    I've made a demo project, however it can't be submit to request. It's built successfully under GRADLE, but unable to build by BUCK.
    Thanks 

     

Regards,
Cong Ling

**Comment by sdwilsh** [comment] 2015-10-01 22:34
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/aapt/MiniAapt.java#L444 is the spot that needs to be fixed, if you'd like to do a PR.

**Comment by congling** [comment] 2015-10-02 00:34
Hi sdwilsh, 
    Thanks for your help.
    I've made a smaller test yesterday, and found out that if I just put '<string name="jconnect.droid.attach">Attach</string>' into 'values/strings.xml' and read it by using res.getString(R.jconnect_droid_attach), it would cost any trouble,
   But when I copy all the res file to the project, it'll reproduce the issue .It's weird.
   However I can't upload the test source code in github.  Do  you need my sample? 
   thx

**Comment by congling** [comment] 2015-10-02 13:38
I found that only if the dot pattern in 'android:id="@+id/xxx.xxx"' will trigger the issue.

**Comment by sdwilsh** [comment] 2015-10-02 16:58
I don't doubt we have a bug.  Based on what you already provided, it looks like we just need to convert `.` to `_` like Gradle and Ant do in the method I linked to above.

**Comment by sdwilsh** [comment] 2015-10-22 21:36
Hey @congling, we added a test yesterday that would have hit the issue you describe but it passes.  Can you make a reproducible test case so we can try to resolve this for you?

**Comment by nayrmi** [comment] 2016-06-14 05:53
Closing since there's no repro now. However, feel free to reactivate if you are able to generate a consistent repro!

**Closed by nayrmi** 2016-06-14 05:53 UTC
Labels: bug
