### ISSUE TITLE
fetching dependencies fails with no zip in path

### ISSUE THREAD

**Issue by elazarl** [facebook/buck#793] opened 2016-06-27 05:36 UTC
When building gerrit-oauth-provider, buck tries to download commos:codec, from some reason it tries to run a bucklet which is a python file in `./bucklets/tools/download_file.py`.

This file contains the line

```python
    check_call(['zip', '-d', args.o] + exclude)
```

Which fails with the following weird error message.

```
../buck/bin/buck build plugin                                                                                                                                              
gerrit2@spark:~/gerrit-oauth-provider$ ./buck/bin/buck build plugin
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...0.5s (14/18 JOBS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //lib/commons:codec__download_bin...  0.1s (running genrule[0.1s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
Traceback (most recent call last):
  File "/home/gerrit2/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 223, in execute
    self.execute_entry(entry_point, args)
  File "/home/gerrit2/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 271, in execute_entry
    runner(entry_point)
  File "/home/gerrit2/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 288, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bucklets/tools/download_file.py", line 174, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:
genrule
```

When installing zip all is well, but it's seems that a better error message is needed. Happened with latest buck to this date.

PS

I haven't the slightest idea why a Java build tool would shell out to PEX python packages, and even if it does, why would it shell out to zip executable instead of using `zipfile` from python stdlib. I also have no idea whether it's buck's fault, gerrit-auth-provider's fault, Ubuntu's fault, or #brexit voter's fault.

But what I know is, this gave me a very bad PR for buck as a user. Bottom line is, simple build failed with a weird error which is hard to understand. So even if it's not buck's direct fault I thought buck developer would be happy to hear about it, and fix the documentation or the ecosystem.

**Comment by Coneko** [comment] 2016-06-27 14:34
I wish I could move issues across repos, anyway this should be the right one: https://github.com/davido/bucklets .

As far as the error message goes, the formatting is a bit confusing, as `BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:` makes it look like the reason for why it failed is `genrule` but it's actually the whole stack trace above.

`genrule` is a target type that is used to execute arbitrary code during the build, used to integrate tools that do not have native Buck integration (https://buckbuild.com/rule/genrule.html). Since Buck cannot interpret the output of the command it runs it will just print it out.

I hope this explains everything, if it doesn't feel free to ask for clarifications, I will close the issue in the meantime as there is no action for us to take.

**Closed by Coneko** 2016-06-27 14:34 UTC

**Comment by elazarl** [comment] 2016-06-28 04:50
What I would do is, give a detailed trace of where the error has occurred.

For example, in our case:

```
In file included from
BUCK:2:include_defs('//bucklets/maven_jar.bucklet')
In
bucklets/gerrit_plugin.bucklet:132:    genrule(
      name = '%s-static' % name,
      cmd = 'mkdir -p $TMP/static' +
        ';unzip -qd $TMP/static $(location %s)' %
        ':%s__gwt_application' % name +
        ';cd $TMP' +
        ';zip -qr $OUT .',
      out = '%s-static.zip' % name,
    )

genrule command execution failed with:
```

That's way, even someone not familiar with buck's internal, could easily spot the error, understand where it came from, and even fix it.

Moreover, it would give me a pointer to the genrule command so that I'll be able to look for documentation about it.

Does it make sense?

**Comment by sdwilsh** [comment] 2016-06-28 14:44
The problem is that Buck isn't parsing the build file (it's parsed in 
Python), so it has no idea about any of the contents.  It just gets a 
JSON-like representation of the build rules.

**Comment by elazarl** [comment] 2016-06-28 16:44
Can't the JSON include more information about the build rules?
At least "going to run command X"?
Similar to DWARF at ELF files?
Seems to me useful for more things.

**Comment by sdwilsh** [comment] 2016-07-05 17:52
The command that is going to be ran isn't even a factor when parsing 
build files, so it'd be have to be passed in.  It'd be a lot of work to 
make something like this possible given how the code is constructed today.
