### ISSUE TITLE
Allow mixed java and kotlin sources in kotlin_library() target.

### ISSUE THREAD

**Issue by dsyang** [facebook/buck#1037] opened 2016-12-05 18:53 UTC
see comments in #948 

This would have to be a two step process. Run `kotlinc` on the kotlin sources first, then pass the result into `javac` and compile the java sources. https://discuss.kotlinlang.org/t/compiling-mixed-java-and-kotlin-files-on-the-command-line/1553

**Comment by kageiit** [comment] 2016-12-05 19:23
This is kinda related to how kapt works as well. kapt in the gradle plugin generates an abi jar of all the kotlin sources so javac annotation processing can run with that on the classpath.

It then runes kotlinc with the generated sources on the classpath so that kotlin code can actually refer to generated code from the javac annotation processor step.

**Comment by brettwooldridge** [comment] 2016-12-15 05:41
@dsyang @kageiit I have coincidentally started working on in-VM compilation of kotlin rather than shelling out, based on code hijacked from the [kotlin ant task](https://github.com/brettwooldridge/kotlin/blob/master/ant/src/org/jetbrains/kotlin/ant/KotlinCompilerAdapter.kt).  I can sweep up this issue at the same time.

**Comment by dsyang** [comment] 2016-12-15 05:48
That's awesome @brettwooldridge!

**Comment by brettwooldridge** [comment] 2016-12-15 05:51
@dsyang As I understand it, this is basically a sequential compilation currently, correct?  Meaning Kotlin and then Java.  So the following, in a single project would not be supported?
```
A.kt extends B.java
B.java references C.kt
```

**Comment by brettwooldridge** [comment] 2016-12-15 05:56
@dsyang I've got big plans for the coming weeks. 👍  Probably before this feature I will tackle ``autodeps`` support, which entails prying into ``kotlin-compiler.jar`` to get at the AST parser.

**Comment by dsyang** [comment] 2016-12-15 05:57
It is sequential but I believe `kotlinc` will load and Java classes
referenced by a kotlin file when compiling it (see the link above).

Your example should work as long as kotlinc can find B.java

**Comment by dsyang** [comment] 2016-12-15 05:58
@brettwooldridge can't wait!

**Comment by kageiit** [comment] 2016-12-15 06:04
@brettwooldridge the use case you mentioned should be supported. Kotlin adds all java sources to the class path when compiling and then the kotlin classes are added to the javac class path. So cross cutting dependencies between java and kotlin source should be fully supported. This is already possible in gradle and you can verify the same. It is still sequential.

With the availability of kapt3 in kotlin compiler, there are additional steps before where kotlin generates the java stubs from kotlin classes required for javac annotation processing to work.

**Comment by kageiit** [comment] 2016-12-16 08:46
> Probably before this feature I will tackle autodeps support, which entails prying into kotlin-compiler.jar to get at the AST parser.

@brettwooldridge https://github.com/JetBrains/uast might be useful for this task. It can provide a universal AST for both java and kotlin code

**Comment by brettwooldridge** [comment] 2016-12-16 15:18
@kageiit Thanks.  I stumbled across that, and didn't realize what I was looking at, and moved on...

**Comment by brettwooldridge** [comment] 2017-03-21 11:13
If any one of you is adventurous, you can try my *kotlin-compiler2* branch (in my fork).  It does not support mixed compilation yet but will soon.  It uses the kotlin compiler daemon under the covers (1.1 required).

**Comment by kageiit** [comment] 2017-03-21 16:47
@brettwooldridge can the daemon client not be run as part of the buck daemon? It seems weird to have a daemon separate from the one in buck which `buck kill` may still leave intact and can lead to weird non reproducible build artifacts.

**Comment by brettwooldridge** [comment] 2017-03-22 00:34
@kageiit I'll look into it, seems feasible.  Still interested in feedback on performance.

**Comment by brettwooldridge** [comment] 2017-03-22 15:29
@kageiit If you are interested in testing the latest changes, I have updated my ``kotlin-compiler2`` branch of my [fork](https://github.com/brettwooldridge/buck).  The Kotlin compile daemon is now started in-process with the buck daemon.

It seems to work on my current Kotlin project.  Successive runs, deleting *buck-out* between, saw decreasing compile times:
```
[-] PROCESSING BUCK FILES...FINISHED 0.2s [100%] 🏖  Watchman reported no changes
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 27.8s [100%] (453/453 JOBS, 453 UPDATED, 453 [100.0%] CACHE MISS)
    Details: http://localhost:53857/trace/548a1968-c52b-4bfa-bb01-48894bd91c97

[-] PROCESSING BUCK FILES...FINISHED 0.0s 🏖  (Watchman reported no changes)
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 19.6s [100%] (453/453 JOBS, 453 UPDATED, 453 [100.0%] CACHE MISS)
    Details: http://localhost:53857/trace/570bf15f-ebe9-43de-ab20-39635dcb2179

[-] PROCESSING BUCK FILES...FINISHED 0.0s 🏖  (Watchman reported no changes)
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 18.2s [100%] (453/453 JOBS, 453 UPDATED, 453 [100.0%] CACHE MISS)
    Details: http://localhost:53857/trace/2a881c98-2db2-4bce-be67-b3f5d338c77c

[-] PROCESSING BUCK FILES...FINISHED 0.0s 🏖  (Watchman reported no changes)
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 16.5s [100%] (453/453 JOBS, 453 UPDATED, 453 [100.0%] CACHE MISS)
    Details: http://localhost:53857/trace/00e7dd26-81fb-41eb-bf96-d59959e61d6e
```

**Comment by kageiit** [comment] 2017-03-22 17:13
Nice. I will test it out on our codebase. we have one big kotlin module right now that we can try this on.

**Comment by brettwooldridge** [comment] 2017-03-22 17:19
@kageiit I'm sure you know the drill, but just in case, I have been running:
```
cd <buck>
ant clean ; ant ; bin/buck build buck
```
And then doing ``export PATH=<buck>/bin:$PATH`` in the shell I build my Kotlin project in.

**Comment by kageiit** [comment] 2017-03-22 17:20
Should i be changing anything in `.buckconfig`? like kotlin_home etc? Currently, kotlin jars etc. are checked in and buck is pointing to those

**Comment by brettwooldridge** [comment] 2017-03-22 17:27
Good question.  I have nothing in my ``.buckconfig``.  There is [code there](https://github.com/brettwooldridge/buck/blob/kotlin-compiler2/src/com/facebook/buck/jvm/kotlin/KotlinBuckConfig.java) to try to find the Kotlin jars, and you should be able to explicitly define ``daemon_jar``, ``compiler_jar``, and ``runtime_jar`` locations.  Untested.

**Comment by kageiit** [comment] 2017-03-22 17:34
Sure. ill update with results

**Comment by kageiit** [comment] 2017-03-23 03:47
@brettwooldridge Compared the performance with external kotlinc vs the in memory one with the daemon. Its a big improvement ~3x even after removing buck-out. The kotlin daemon seems to be no longer active when i kill the buck daemon as expected.

**Comment by kageiit** [comment] 2017-03-23 03:49
The kotlin-compler2 branch seems to have some merge conflicts with master of buck though, which you might want to fix.

**Comment by brettwooldridge** [comment] 2017-03-23 11:13
@kageiit I'm not surprised.  I rebased a few weeks back onto a stable commit.  Once I get the code closer to where it needs to be I'll fight the rebase fight (unless someone wants to do it can give me a pull request).

Great to hear about the speed improvement!

Somebody might try sending mixed sources into the target (*.java and *.kt), I haven't gotten around to trying it yet, but there is no code explicitly forbidding it.

**Comment by brettwooldridge** [comment] 2017-03-24 11:01
@kageiit @dsyang @ilya-g Does anybody know what the specific purpose of the ``CompilerId`` Kotlin class is, for example, ``CompilerId compilerId = CompilerId.makeCompilerId(compilerIdPaths)``.

My current code [has a hack](https://github.com/brettwooldridge/buck/blob/kotlin-compiler2/src/com/facebook/buck/jvm/kotlin/KotlincShim.java#L91) to work around a strange issue I encountered...

I thought it was sufficient to [start one Kotlin compiler daemon instance](https://github.com/brettwooldridge/buck/blob/kotlin-compiler2/src/com/facebook/buck/jvm/kotlin/KotlincShim.java#L41), but if I do so, I get sporadic failures [trying to connect](https://github.com/brettwooldridge/buck/blob/kotlin-compiler2/src/com/facebook/buck/jvm/kotlin/KotlincShim.java#L92).  The *hack* is, if I get a connection failure, I [start another in-process daemon instance](https://github.com/brettwooldridge/buck/blob/kotlin-compiler2/src/com/facebook/buck/jvm/kotlin/KotlincShim.java#L101) and try the connection again.

I thought this might have something to do with the ``ComplierId``, if for example, that is supposed to somehow be unique per client-invocation, but looking at it, that doesn't seem so...

It may be a simple race condition within the compiler daemon itself, as Buck probably tries to initiate several connections in extremely rapid succession (i.e.. simultananeously).

Any ideas?

**Comment by ligee** [comment] 2017-03-28 10:07
@brettwooldridge `CompilerId` is used to search compatible running daemons. And this is most likely has nothing to do with the issues you're having.

There is one known racing condition which is usually marked with "Daemon is dying" message in the `reportingTargets`. It happens when several daemons are started in parallel, and then they are making internal elections to limit the number of compatible daemon processes in the memory.

You can use the new (since 1.1.1) atomic `connectAndLease function that should not fail in these cases. The price will be that the parallelly started compatible daemons will all stay in memory until the appropriate sessions are released (use `releaseSession` for that.)

Or use your workaround, it is, in fact, ok for now.

Please note that the compiler and daemon APIs are not yet stable and/or complete. We are working on bringing it to the supportable state, but we're not there yet.

**Comment by brettwooldridge** [comment] 2017-03-28 11:10
@ligee Thanks!  That leads to more questions.  We want the daemon to live for the life of the buckd process (i.e. possibly hours or days).  If I use the lease, what does the daemon do when the last lease is released?  Does it exit?  

Another question.  It seems we need multiple daemon instances running, is that expected?  I thought we could start one daemon instance, and then run compiles from N number of threads, but it seems to want multiple daemons, possibly one per thread.  Is that expected?

**Comment by ligee** [comment] 2017-03-29 14:31
@brettwooldridge There are two main "hooks" to the daemon lifetime. 
The first is the `clientAliveFlagFile'  that you pass to the connect functions. When the file is deleted, the daemon stops. You can use it to ensure that daemon will be stopped when the `buckd` process is stopped. (I'm usually calling `deleteOnExit` on this file) But the daemon can exit earlier if some timeout occurs, e.g. by default if there are no compilations happen within 2 hours.
The second is the leased sessions. The daemon will not exit on the timeouts while there are leased sessions. But I wouldn't recommend keeping a session open all the time. To my mind, the more economical solution would be to call `connectAndLease` each time you need a compilation (or maybe several ones in a row).

The compilations can be run in parallel on the single daemon instance if required `compilerId` (thus - compiler jar basically) is the same. There is right now no control on a number of the compilations that can run in parallel. The only way to do it now is to do it is to implement management on your side, and if required run a fresh daemon by specifying different discovery directory (`DaemonOptions.runFilesPath`).

**Comment by brettwooldridge** [comment] 2017-03-30 18:49
@kageiit I have rebased my changes onto master; what a pain in the a**.  I also implemented the daemon leasing scheme suggested by @ligee.  That means that Kotlin 1.1.1 is required.

The new branch is ``kotlin-compiler`` (not ``kotlin-compiler2``).  It seems to be working, but I know the code still needs some work.

3:45am here so I'm knocking off for tonight.  Let me know how it works for you.

**Comment by kageiit** [comment] 2017-03-30 18:50
Sure. I'll give it a whirl. Thanks for all the efforts!

**Comment by dsyang** [comment] 2017-04-05 17:03
Hey @brettwooldridge this is awesome! 

Would you be comfortable putting your changes in `kotlin-compiler` up in a PR so we could start reviewing it?

I know there's still some work that you'd like to do but this could make it easier to merge later down the line.

**Comment by kageiit** [comment] 2017-04-05 18:02
@brettwooldridge Sorry forgot to report back. The latest changes look good

**Comment by brettwooldridge** [comment] 2017-04-05 23:54
@dsyang @kageiit I ditched the Kotlin daemon changes.  buckd is already a daemon, so now I directly instantiate a K2JVMCompiler that is kept alive for the lifetime of buckd. Performance seems to be identical to the previous incarnation but the code is *substantially* simpler.

Give it a try if you have a chance.

@dsyang I'll try to put together a pull request.

**Comment by kageiit** [comment] 2017-04-05 23:56
sounds great. Ill give it a try

**Comment by brettwooldridge** [comment] 2017-04-11 04:55
@dsyang @kageiit Can either of you shed light on [what this is about](https://github.com/facebook/buck/blob/a1b1a416fcc3f12360c9d44a704d805a3927ccc6/src/com/facebook/buck/android/AndroidLibraryDescription.java#L63), and how it is used from an external .buckconfig or BUCK file perspective?

**Comment by kageiit** [comment] 2017-04-11 06:37
@brettwooldridge I think this was added a while ago as mixed source compilation was not possible before. So that enum was a way of indicating that only `.kt` or `.java` files can be part of the `srcs` i.e there cannot be a mix of multiple language types. I think that limitation can be lifted if mixed source compilation is possible.

**Comment by brettwooldridge** [comment] 2017-04-12 07:43
@kageiit It seems my mental image if "mixed source" was off (I don't use mixed source).  Looking at the existing Kotlin build tasks (ant/maven), "mixed source" compilation seems to simply mean "invoke kotlinc, then invoke javac".

So, in summary, is this issue basically about being able to do the following?
```
kotlin_library(
    name = 'project',
    srcs = glob(['**/*.kt', '**/*.java']),
)
```
With the result being a .jar file of compiled Kotlin and Java classes?

**Comment by kageiit** [comment] 2017-04-12 07:50
Yep

**Comment by brettwooldridge** [comment] 2017-04-12 08:04
@kageiit Ok, thanks.  That's next on the agenda then.

**Comment by runningcode** [comment] 2017-05-18 01:31
I tried out this branch and I got an error when passing mixed sources to it. `error: source entry is not a Kotlin file`

**Comment by dsyang** [comment] 2017-05-18 02:11
@runningcode Not sure what you mean by this branch. You can't build a target with mixed sources in the master branch (or any branch right now).  This issue is tracking that feature.  @brettwooldridge  has the most context right now. IIRC #1283 is the first step towards getting this to work.

**Comment by runningcode** [comment] 2017-05-18 02:16
Ah, I meant I tried passing java sources and kotlin sources to a module on the `brettwooldridge:kotlin-compiler2` branch.

**Comment by dsyang** [comment] 2017-05-18 02:17
I'm pretty sure that branch doesn't enable mixed sources yet either.

**Closed** 2017-06-13 23:26 UTC
