### ISSUE TITLE
Buck version in Brew has not been updated since March

### ISSUE THREAD

**Issue by mlostekk** [facebook/buck#835] opened 2016-08-07 14:17 UTC
basically thats it... 

`buck --version` gives `BUILD FAILED: Failed to read NDK version from /Users/mlostek/Library/Android/sdk/ndk-bundle`

any suggestions?

**Comment by Coneko** [comment] 2016-08-07 20:59
Does that directory exist? What are the values of the `ANDROID_SDK` and `ANDROID_NDK` environment variables?

**Comment by mlostekk** [comment] 2016-08-07 21:27
Yep. Sure. I am already working with Android Studio and every path is set up correctly

```
echo $ANDROID_SDK
/Users/mlostek/Library/Android/sdk

echo $ANDROID_NDK
/Users/mlostek/Library/Android/sdk/ndk-bundle
```

somehow i guess i cannot update buck with brew correctly.

when i remove the ANDROID_NDK path variable, `buck --version`returns

`buck version v2016.03.28.01`

**Comment by k21** [comment] 2016-08-08 09:44
This is almost definitely caused by the version in Brew being pretty old. Support for `source.properties` was added in 7a6fba112f62abf865c27e3dd91d6e5d97625d95 in April, the version in Brew is from March. I am going to change this issue to track the Brew update instead since the reported issue has been fixed in the master branch.

**Comment by mlostekk** [comment] 2016-08-08 10:40
Well, even if i install the version from git, there seem to be issues with the NDK... 

When i run brew install --HEAD buck then the logfile of the buck build tells me the following (ant build runs fine)

```
2016-08-08 12:30:13 +0200

./bin/buck
build
buck

Not using buckd because watchman isn't installed.
[2016-08-08 12:30:20.756][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: /Users/mlostek/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
    at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
    at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:577)
    at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:626)
    at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:378)
    at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:137)
    at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:101)
    at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:339)
    at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:233)
    at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:48)
    at com.facebook.buck.rules.Cell.<init>(Cell.java:115)
    at com.facebook.buck.rules.Cell.createCell(Cell.java:159)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:829)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:610)
    at com.facebook.buck.cli.Main.main(Main.java:1679)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)


HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 850db4ebf473738ffba8424065d62954d3c95dd1
Last commit: 35 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6756fa5bfe3ed5881831398ae98cf6190cdd317
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 0
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66, 1.6.0_65-b14-468
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CFLAGS: -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include/darwin
CXXFLAGS: -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include/darwin
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.11
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.11
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin:/usr/local/Library/Homebrew/shims/super:/usr/local/opt/ant/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by k21** [comment] 2016-08-08 10:46
Does `/Users/mlostek/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc` exist and is it executable?

**Comment by mlostekk** [comment] 2016-08-08 10:49
Ah. It seems that `arm-linux-androideabi-4.8` is not existing. There is `arm-linux-androideabi-4.9`

**Comment by k21** [comment] 2016-08-08 10:56
cc @aiked who has been the last person to look at the NDK platform support.

**Comment by aiked** [comment] 2016-08-10 10:01
Hello @mlostekk,
Is it possible for you to give me the logs of the failed build? I'm afraid that I don't have enough data  from the Homebrew log. The log can be found under /buck-out/log and the problematic command.

**Comment by k21** [comment] 2016-08-10 10:06
@mlostekk, try adding this in your `.buckconfig` file:
```
[ndk]
  gcc_version = 4.9
```
Let me know if it helps.

**Comment by mlostekk** [comment] 2016-08-10 14:25
Well, i cant even build / install buck. Where to set the gcc version  to 4.9? Is there a global buckconfig file somewhere?

Well, the title of this issue is now misleading. Thats why i created another issue for the installation / build process of buck itself.

https://github.com/facebook/buck/issues/841

You can find the full log over there.

**Comment by artemyarulin** [comment] 2016-08-28 14:56
Even though the issue was a different one, but what about putting v2016.04.18.01 to Brew? I was thinking to make a PR, but cannot figure out what sha256 should be here https://github.com/facebook/homebrew-fb/blob/master/buck.rb#L15

**Comment by mlostekk** [comment] 2016-09-01 21:03
I am leaving buck behind. I was not able to get react native running with buck after approx. 8 hours of trying. And it seems that buck maintenance is too irregular.

**Comment by artemyarulin** [comment] 2016-09-02 05:27
@sdwilsh As you are always updating Buck in https://github.com/facebook/homebrew-fb would you mind to do it again? Or just tell me how to calculate hash on https://github.com/facebook/homebrew-fb/blob/master/buck.rb#L15 and I'll make a PR, thanks.

**Comment by k21** [comment] 2016-09-02 09:29
I am sorry to hear that @mlostekk. I am unfortunately not very familiar with React Native projects myself.

I am still going to look into updating the version in Homebrew when I have an opportunity. @artemyarulin I think that hash is supposed to be the hash of the downloaded binary:
```
$ shasum -a 256 buck-2016.03.28.01.yosemite_or_later.bottle.tar.gz
c2937782ea161f92c438d2951b21acaa632380f2ea80ed25b5b7cd16863e6211  buck-2016.03.28.01.yosemite_or_later.bottle.tar.gz
```

**Comment by k21** [comment] 2016-09-02 13:22
I have released a new version of Buck on GitHub and updated our Hombrew tap. Installing Buck from Brew should now get you a recent version.

**Closed by k21** 2016-09-02 13:22 UTC

**Comment by artemyarulin** [comment] 2016-09-02 13:23
Thank you very much @k21!

**Comment by mlostekk** [comment] 2016-09-02 18:17
Thank you very much. Do you guys have any examples for **working** buck configurations for react native projects anywhere?

**Comment by sdwilsh** [comment] 2016-09-06 22:14
@mlostekk - we don't currently have anything for that.  There might be some code in tests in the react-native project itself.  Reaching out there might be best, as that's more specific to that domain than to Buck.

**Comment by mlostekk** [comment] 2016-09-08 08:18
Yep, [already did that](http://stackoverflow.com/questions/39183002/buckbuild-tutorials-in-order-to-get-nuclide-and-react-native-running).. thanks anyways
