### ISSUE TITLE
New way to compute buck hash digest breaks network cache

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1605] opened 2017-10-26 21:46 UTC
Buck recently changed the seed key they use for computing all the cache keys from being the git sha of the buck installation to be a checksum of all the jars buck depends on.

https://github.com/facebook/buck/commit/eadb4fc6d9b22d956547e05a56310843ce12fe94

Problem is ant build on mac and ant build on linux at the same sha produce different checksums in this methodology. This was leading us to have different cache keys on ci vs local and even across ci machines in some cases depending on things like jdk version installed etc.

We need to remove the non deterministic/system bits from the computation here otherwise anyone using buck network caches will see their cache become totally ineffective

**Comment by kageiit** [comment] 2017-10-26 21:47
@styurin @ttsugriy 

cc @cwoodwar6 @seanabraham @artem-zinnatullin Heads up if you updated buck recently to check your cache keys across machines

**Comment by kageiit** [comment] 2017-10-26 21:59
Local java version
```
java -version
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
```

CI java version
```
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by kageiit** [comment] 2017-10-26 22:03
I pushed a workaround to https://github.com/kageiit/buck/tree/revert_cache_key_calculation if anyone needs it while this is being fixed

**Comment by artem-zinnatullin** [comment] 2017-10-26 22:10
@kageiit thanks for heads up! ❤️  

Updated Buck literally 30 minutes ago, uh, will probably just revert it back for now

**Comment by ttsugriy** [comment] 2017-10-26 22:27
thanks for the report @kageiit! @styurin is going to take care of this. Sorry for the hassle.

**Comment by styurin** [comment] 2017-10-27 00:03
One of the issues in including javac-plugin.jar. I have a fix for that. This should solve the problem of using java compilers with different minor versions.

I also plan to add a way to use the old behavior, probably without using the old logic when we collected all local changes to calculate the Buck version.

**Comment by kageiit** [comment] 2017-10-27 01:10
One way to solve the problem would be to use a compiler jar like we do for buck to ensure hermetic builds. Then it wont matter what jdk we run with

**Comment by styurin** [comment] 2017-10-27 02:33
We actually use Eclipse compiler that is in the repository.

**Comment by styurin** [comment] 2017-10-28 05:41
I tried to reproduce the problem with `KotlinLibraryBuilder.class` using the same JDKs, but was unable to do that. In my case these files were identical.

After looking at the class files I found that local class has corrupted `LineNumberTable` in it. Since we build code using Eclipse compiler I suspect there might be some bug in it.

@kageiit Could you double check that you still see a problem with this file, please?

**Comment by kageiit** [comment] 2017-10-28 17:59
I will try on a few other machines and report back. Local file was using oracle jdk on a mac and ci was using openjdk on linux just to make sure you were testing with the same environment

**Comment by styurin** [comment] 2017-11-06 18:09
I'm going to put some changes to revert this logic and have a configuration option to control this behavior.

**Comment by styurin** [comment] 2017-11-07 12:44
Committed 80e39a9f0952d3f960ce239779640063967bf826

**Closed** 2017-11-12 04:17 UTC
